/* ARIA integration seam. Load this file BEFORE script.js.
   ask(query) returns { t:[paragraphs], f?:formula, s:[[docIndex, sectionName, relevance 0-1, passage]] } or null.
   Replace the body of ask() with the real backend call. DEMO is sample data only; delete it when wired. */
const DOCS=["Robotics Fundamentals","Lab Manual — Manipulators","Mobile Robotics & SLAM","ROS Setup Guide","Computer Vision Notes","Sensor Systems Datasheets"];
const CHUNKS=1284;
/* Integration seam. Replace body with the real backend call (Groq + RAG). Demo data only. */
const DEMO=[
{k:/transform|matrix|kinematic/i,t:["A homogeneous transformation matrix combines a rotation and a translation in one 4×4 matrix, so frames chain by simple multiplication.","For each joint, build the matrix from the Denavit–Hartenberg parameters, then multiply the joint matrices from base to end effector."],f:"T = Rz(θ) · Tz(d) · Tx(a) · Rx(α)\nT0n = T01 · T12 · … · T(n-1)n",s:[[0,"Ch. 3 · Rigid Body Motion",.93,"A rigid transformation is captured by a rotation R and a position vector p, stacked into a 4×4 matrix with a bottom row of 0 0 0 1."],[1,"§2.4 · DH Parameters",.88,"Assign frames per link, read off a, α, d and θ, and compose the four elementary transforms in order."]]},
{k:/loop|slam|closure/i,t:["Loop closure is the moment a robot recognises a place it has visited before and uses that to correct accumulated drift in its map."],s:[[2,"Ch. 5 · Back-end Optimisation",.91,"When the current scan matches an earlier keyframe, a new constraint is added to the pose graph and the whole trajectory is re-optimised."]]},
{k:/object|detect|vision/i,t:["Object detection finds what is in an image and where. A network proposes boxes, scores each class, and non-maximum suppression removes overlaps."],s:[[4,"Ch. 7 · Detection Pipelines",.9,"Single-stage detectors predict boxes and class scores in one pass; thresholds on confidence and IoU prune the output."],[5,"Camera Module · Notes",.62,"Frame rate and exposure set limits on how fast an object can move before detection degrades."]]},
{k:/calibrat|arm|procedure/i,t:["Calibrate the arm from its home pose, then verify each joint against the reference mark before running any program."],s:[[1,"§4.1 · Arm Calibration",.95,"Power the controller, drive each joint to its limit switch, zero the encoders, then confirm the pose against the reference mark."],[3,"Driver Setup",.57,"Confirm the controller node is publishing joint states before starting calibration."]]}];
async function ask(q){await new Promise(r=>setTimeout(r,1100));const d=DEMO.find(x=>x.k.test(q));return d?{t:d.t,f:d.f,s:d.s}:null}
